"""target bridge baseline

Revision ID: 0001_target_bridge
Revises:
Create Date: 2026-07-14 00:13:25.303071
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_target_bridge"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_key", sa.String(length=63), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("normalized_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "PREFLIGHTING",
                "PREFLIGHT_FAILED",
                "REVIEW_REQUIRED",
                "PUBLISHING",
                "PUBLISH_FAILED",
                "READY",
                "DELETING",
                "DELETE_FAILED",
                "REJECTED",
                "CANCELLED",
                "DELETED",
                name="document_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "terminal_disposition",
            sa.Enum(
                "CANCELLED",
                "REJECTED",
                "DELETED",
                name="terminal_disposition",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "scan_state",
            sa.Enum(
                "PENDING",
                "CLEAN",
                "INFECTED",
                "ERROR",
                name="scan_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scan_engine", sa.String(length=100), nullable=True),
        sa.Column("scan_signature", sa.String(length=255), nullable=True),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("failure_retryable", sa.Boolean(), nullable=False),
        sa.Column("replaced_by_document_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(state IN ('DELETING', 'DELETE_FAILED') "
            "AND terminal_disposition IS NOT NULL) OR "
            "(state IN ('REJECTED', 'CANCELLED', 'DELETED') "
            "AND terminal_disposition = state) OR "
            "(state NOT IN ('DELETING', 'DELETE_FAILED', 'REJECTED', "
            "'CANCELLED', 'DELETED') AND terminal_disposition IS NULL)",
            name=op.f("ck_documents_terminal_disposition_matches_state"),
        ),
        sa.CheckConstraint(
            "state NOT IN ('REJECTED', 'CANCELLED', 'DELETED') OR storage_key IS NULL",
            name=op.f("ck_documents_terminal_document_has_no_source"),
        ),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_documents_sha256_length")),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_documents_size_bytes_positive")),
        sa.ForeignKeyConstraint(
            ["replaced_by_document_id"],
            ["documents.id"],
            name=op.f("fk_documents_replaced_by_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_collection_sha_state", ["collection_key", "sha256", "state"], unique=False
        )
        batch_op.create_index(
            "ix_documents_collection_state_created",
            ["collection_key", "state", "created_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_state"), ["state"], unique=False)

    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "length(request_sha256) = 64", name=op.f("ck_idempotency_records_request_sha256_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("key", name=op.f("uq_idempotency_records_key")),
    )
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_idempotency_records_resource", ["resource_type", "resource_id"], unique=False
        )

    op.create_table(
        "prepared_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PREPARING",
                "SEALED",
                "FAILED",
                name="revision_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active_qdrant_collection", sa.String(length=255), nullable=False),
        sa.Column("content_profile_id", sa.String(length=128), nullable=False),
        sa.Column("index_profile_id", sa.String(length=128), nullable=False),
        sa.Column("preflight_policy_id", sa.String(length=128), nullable=False),
        sa.Column("formatter_model_id", sa.String(length=255), nullable=False),
        sa.Column("dense_model_id", sa.String(length=255), nullable=False),
        sa.Column("dense_dimension", sa.Integer(), nullable=False),
        sa.Column("sparse_model_id", sa.String(length=255), nullable=False),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("native_text_eligible", sa.Boolean(), nullable=False),
        sa.Column("formatter_complete", sa.Boolean(), nullable=False),
        sa.Column("vector_complete", sa.Boolean(), nullable=False),
        sa.Column("candidate_discovery_complete", sa.Boolean(), nullable=False),
        sa.Column("advisory_complete", sa.Boolean(), nullable=False),
        sa.Column("clear_for_publication", sa.Boolean(), nullable=False),
        sa.Column("incomplete_reasons", sa.JSON(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("expected_point_count", sa.Integer(), nullable=True),
        sa.Column("extraction_sha256", sa.String(length=64), nullable=True),
        sa.Column("markdown_sha256", sa.String(length=64), nullable=True),
        sa.Column("vector_manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("evidence_manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status != 'SEALED' OR (manifest_sha256 IS NOT NULL "
            "AND sealed_at IS NOT NULL AND page_count IS NOT NULL "
            "AND chunk_count IS NOT NULL AND expected_point_count = chunk_count)",
            name=op.f("ck_prepared_revisions_sealed_manifest_complete"),
        ),
        sa.CheckConstraint(
            "chunk_count IS NULL OR chunk_count >= 0",
            name=op.f("ck_prepared_revisions_chunk_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "dense_dimension = 768", name=op.f("ck_prepared_revisions_dense_dimension_target")
        ),
        sa.CheckConstraint(
            "expected_point_count IS NULL OR expected_point_count >= 0",
            name=op.f("ck_prepared_revisions_expected_point_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count >= 0",
            name=op.f("ck_prepared_revisions_page_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_prepared_revisions_revision_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_prepared_revisions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prepared_revisions")),
        sa.UniqueConstraint(
            "document_id", "revision_number", name=op.f("uq_prepared_revisions_document_id")
        ),
    )
    with op.batch_alter_table("prepared_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prepared_revisions_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_prepared_revisions_document_status", ["document_id", "status"], unique=False
        )

    op.create_table(
        "tombstones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("collection_key", sa.String(length=63), nullable=False),
        sa.Column(
            "disposition",
            sa.Enum(
                "CANCELLED",
                "REJECTED",
                "DELETED",
                name="tombstone_disposition",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(source_sha256) = 64", name=op.f("ck_tombstones_source_sha256_length")
        ),
        sa.CheckConstraint(
            "manifest_sha256 IS NULL OR length(manifest_sha256) = 64",
            name=op.f("ck_tombstones_manifest_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_tombstones_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tombstones")),
        sa.UniqueConstraint("document_id", name=op.f("uq_tombstones_document_id")),
    )
    with op.batch_alter_table("tombstones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tombstones_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "KEEP",
                "REPLACE",
                "CANCEL",
                name="decision_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_document_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_record_id", sa.Uuid(), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(action = 'REPLACE' AND target_document_id IS NOT NULL) OR "
            "(action IN ('KEEP', 'CANCEL') AND target_document_id IS NULL)",
            name=op.f("ck_decisions_replacement_target_matches_action"),
        ),
        sa.CheckConstraint(
            "length(prepared_manifest_sha256) = 64",
            name=op.f("ck_decisions_prepared_manifest_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_decisions_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["idempotency_record_id"],
            ["idempotency_records.id"],
            name=op.f("fk_decisions_idempotency_record_id_idempotency_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_decisions_prepared_revision_id_prepared_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_document_id"],
            ["documents.id"],
            name=op.f("fk_decisions_target_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint(
            "idempotency_record_id", name=op.f("uq_decisions_idempotency_record_id")
        ),
        sa.UniqueConstraint("prepared_revision_id", name=op.f("uq_decisions_prepared_revision_id")),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decisions_document_id"), ["document_id"], unique=False)

    op.create_table(
        "extracted_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("layout_text", sa.Text(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "character_count >= 0", name=op.f("ck_extracted_pages_character_count_nonnegative")
        ),
        sa.CheckConstraint(
            "length(text_sha256) = 64", name=op.f("ck_extracted_pages_text_sha256_length")
        ),
        sa.CheckConstraint(
            "page_number >= 1", name=op.f("ck_extracted_pages_page_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_extracted_pages_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_pages")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "page_number",
            name=op.f("uq_extracted_pages_prepared_revision_id"),
        ),
    )
    with op.batch_alter_table("extracted_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extracted_pages_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "formatter_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "VALID",
                "FAILED",
                name="formatter_batch_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("page_slices", sa.JSON(), nullable=False),
        sa.Column("source_manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("response_sha256", sa.String(length=64), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("validation_errors", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_formatter_batches_attempt_positive")),
        sa.CheckConstraint(
            "batch_index >= 0", name=op.f("ck_formatter_batches_batch_index_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_formatter_batches_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_formatter_batches")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "batch_index",
            "attempt",
            name=op.f("uq_formatter_batches_prepared_revision_id"),
        ),
    )
    with op.batch_alter_table("formatter_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_formatter_batches_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "index_outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target",
            sa.Enum(
                "ACTIVE",
                "SCREENING",
                name="index_target",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "UPSERT",
                "PUBLISH",
                "DELETE",
                name="index_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("qdrant_collection", sa.String(length=255), nullable=False),
        sa.Column("expected_points", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "APPLIED",
                "SUPERSEDED",
                name="outbox_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expected_points >= 0", name=op.f("ck_index_outbox_expected_points_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_index_outbox_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_index_outbox_prepared_revision_id_prepared_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_outbox")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "target",
            "action",
            "qdrant_collection",
            name=op.f("uq_index_outbox_prepared_revision_id"),
        ),
    )
    with op.batch_alter_table("index_outbox", schema=None) as batch_op:
        batch_op.create_index("ix_index_outbox_claim", ["state", "id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_index_outbox_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_index_outbox_document_target", ["document_id", "target"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_index_outbox_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_index_outbox_state"), ["state"], unique=False)

    op.create_table(
        "prepared_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("matched_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "ACTIVE",
                "SCREENING",
                name="candidate_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("max_cosine", sa.Float(), nullable=False),
        sa.Column("bm25_score", sa.Float(), nullable=False),
        sa.Column("fused_score", sa.Float(), nullable=False),
        sa.Column("matched_chunk_pairs", sa.JSON(), nullable=False),
        sa.Column("document_snapshot", sa.JSON(), nullable=False),
        sa.CheckConstraint("rank >= 1", name=op.f("ck_prepared_candidates_rank_positive")),
        sa.ForeignKeyConstraint(
            ["matched_document_id"],
            ["documents.id"],
            name=op.f("fk_prepared_candidates_matched_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_prepared_candidates_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prepared_candidates")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "matched_document_id",
            name=op.f("uq_prepared_candidates_prepared_revision_id"),
        ),
    )
    with op.batch_alter_table("prepared_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prepared_candidates_matched_document_id"),
            ["matched_document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_prepared_candidates_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "prepared_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("heading_path", sa.JSON(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_prepared_chunks_chunk_index_nonnegative")
        ),
        sa.CheckConstraint(
            "length(text_sha256) = 64", name=op.f("ck_prepared_chunks_text_sha256_length")
        ),
        sa.CheckConstraint(
            "page_end >= page_start", name=op.f("ck_prepared_chunks_page_range_ordered")
        ),
        sa.CheckConstraint("page_start >= 1", name=op.f("ck_prepared_chunks_page_start_positive")),
        sa.CheckConstraint(
            "token_count > 0 AND token_count <= 384",
            name=op.f("ck_prepared_chunks_token_count_target_bound"),
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_prepared_chunks_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prepared_chunks")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "chunk_index",
            name=op.f("uq_prepared_chunks_prepared_revision_id"),
        ),
    )
    with op.batch_alter_table("prepared_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prepared_chunks_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "prepared_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("slices", sa.JSON(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("markdown_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_projection_sha256", sa.String(length=64), nullable=False),
        sa.Column("markdown_projection_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(markdown_projection_sha256) = 64",
            name=op.f("ck_prepared_pages_markdown_projection_sha256_length"),
        ),
        sa.CheckConstraint(
            "length(markdown_sha256) = 64", name=op.f("ck_prepared_pages_markdown_sha256_length")
        ),
        sa.CheckConstraint(
            "length(source_projection_sha256) = 64",
            name=op.f("ck_prepared_pages_source_projection_sha256_length"),
        ),
        sa.CheckConstraint("page_number >= 1", name=op.f("ck_prepared_pages_page_number_positive")),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_prepared_pages_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prepared_pages")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "page_number",
            name=op.f("uq_prepared_pages_prepared_revision_id"),
        ),
    )
    with op.batch_alter_table("prepared_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prepared_pages_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "publication_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("active_qdrant_collection", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UPSERTED",
                "VERIFIED",
                "FAILED",
                name="publication_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expected_points", sa.Integer(), nullable=False),
        sa.Column("verified_points", sa.Integer(), nullable=True),
        sa.Column("payload_revision_verified", sa.Boolean(), nullable=False),
        sa.Column("vector_schema_verified", sa.Boolean(), nullable=False),
        sa.Column("screening_zero_verified", sa.Boolean(), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status != 'VERIFIED' OR (verified_points = expected_points "
            "AND payload_revision_verified = 1 AND vector_schema_verified = 1 "
            "AND screening_zero_verified = 1 AND verified_at IS NOT NULL)",
            name=op.f("ck_publication_records_verified_publication_complete"),
        ),
        sa.CheckConstraint(
            "expected_points >= 0", name=op.f("ck_publication_records_expected_points_nonnegative")
        ),
        sa.CheckConstraint(
            "verified_points IS NULL OR verified_points >= 0",
            name=op.f("ck_publication_records_verified_points_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_publication_records_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_publication_records_prepared_revision_id_prepared_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_records")),
        sa.UniqueConstraint(
            "prepared_revision_id", name=op.f("uq_publication_records_prepared_revision_id")
        ),
    )
    with op.batch_alter_table("publication_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publication_records_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "revision_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_revision_artifacts_sha256_length")),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_revision_artifacts_sequence_nonnegative")
        ),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_revision_artifacts_size_bytes_positive")
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_revision_artifacts_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision_artifacts")),
        sa.UniqueConstraint(
            "prepared_revision_id",
            "kind",
            "sequence",
            name=op.f("uq_revision_artifacts_prepared_revision_id"),
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_revision_artifacts_storage_key")),
    )
    with op.batch_alter_table("revision_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_revision_artifacts_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "work_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=True),
        sa.Column("replacement_target_document_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_record_id", sa.Uuid(), nullable=True),
        sa.Column(
            "operation_type",
            sa.Enum(
                "PREFLIGHT",
                "PUBLISH",
                "DELETE",
                name="operation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="operation_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "phase",
            sa.Enum(
                "QUEUED",
                "EXTRACTING",
                "CHECKING_ELIGIBILITY",
                "PACKING_FORMATTER_BATCHES",
                "FORMATTING_MARKDOWN",
                "VALIDATING_MARKDOWN",
                "CHUNKING_MARKDOWN",
                "EMBEDDING_DENSE",
                "EMBEDDING_SPARSE",
                "UPSERTING_SCREENING_POINTS",
                "DISCOVERING_CANDIDATES",
                "CLASSIFYING_CANDIDATES",
                "SEALING_REVISION",
                "AWAITING_DECISION",
                "UPSERT_ACTIVE_POINTS",
                "VERIFY_ACTIVE_POINTS",
                "REMOVE_SCREENING_POINTS",
                "VERIFY_SCREENING_REMOVAL",
                "DELETE_ACTIVE_POINTS",
                "VERIFY_ACTIVE_ZERO",
                "DELETE_SCREENING_POINTS",
                "VERIFY_SCREENING_ZERO",
                "PURGE_STORAGE",
                "COMMIT_TOMBSTONE",
                "COMPLETE",
                name="operation_phase",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("phase_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_work_operations_attempt_positive")),
        sa.CheckConstraint(
            "phase_started_at >= created_at",
            name=op.f("ck_work_operations_phase_started_not_before_creation"),
        ),
        sa.CheckConstraint(
            "operation_type != 'DELETE' OR priority = 0",
            name=op.f("ck_work_operations_delete_priority_high"),
        ),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_work_operations_priority_nonnegative")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_work_operations_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["idempotency_record_id"],
            ["idempotency_records.id"],
            name=op.f("fk_work_operations_idempotency_record_id_idempotency_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_work_operations_prepared_revision_id_prepared_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["replacement_target_document_id"],
            ["documents.id"],
            name=op.f("fk_work_operations_replacement_target_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_operations")),
        sa.UniqueConstraint(
            "document_id", "operation_type", "attempt", name=op.f("uq_work_operations_document_id")
        ),
        sa.UniqueConstraint(
            "idempotency_record_id", name=op.f("uq_work_operations_idempotency_record_id")
        ),
    )
    with op.batch_alter_table("work_operations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_work_operations_claim", ["state", "priority", "created_at", "id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_operations_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_work_operations_lease", ["state", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_operations_operation_type"), ["operation_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_operations_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_work_operations_state"), ["state"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_audit_events_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["work_operations.id"],
            name=op.f("fk_audit_events_operation_id_work_operations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_events_document_time", ["document_id", "occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )

    op.create_table(
        "candidate_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "DETERMINISTIC",
                "CLASSIFIER",
                "VERIFIER",
                "INCOMPLETE",
                name="evidence_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["prepared_candidates.id"],
            name=op.f("fk_candidate_evidence_candidate_id_prepared_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_candidate_evidence_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_evidence")),
        sa.UniqueConstraint(
            "candidate_id", "kind", name=op.f("uq_candidate_evidence_candidate_id")
        ),
    )
    with op.batch_alter_table("candidate_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_evidence_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_candidate_evidence_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    op.create_table(
        "deletion_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=True),
        sa.Column("publication_record_id", sa.Uuid(), nullable=True),
        sa.Column(
            "terminal_disposition",
            sa.Enum(
                "CANCELLED",
                "REJECTED",
                "DELETED",
                name="deletion_terminal_disposition",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active_qdrant_collection", sa.String(length=255), nullable=False),
        sa.Column("screening_qdrant_collection", sa.String(length=255), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "DELETE_ACTIVE_POINTS",
                "VERIFY_ACTIVE_ZERO",
                "DELETE_SCREENING_POINTS",
                "VERIFY_SCREENING_ZERO",
                "PURGE_STORAGE",
                "COMMIT_TOMBSTONE",
                name="deletion_phase",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active_zero_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("screening_zero_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storage_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "active_qdrant_collection != screening_qdrant_collection",
            name=op.f("ck_deletion_progress_physical_targets_distinct"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_deletion_progress_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_deletion_progress_prepared_revision_id_prepared_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["publication_record_id"],
            ["publication_records.id"],
            name=op.f("fk_deletion_progress_publication_record_id_publication_records"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_progress")),
        sa.UniqueConstraint("document_id", name=op.f("uq_deletion_progress_document_id")),
    )
    with op.batch_alter_table("deletion_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deletion_progress_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "prepared_chunk_vectors",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("prepared_revision_id", sa.Uuid(), nullable=False),
        sa.Column("dense_dimension", sa.Integer(), nullable=False),
        sa.Column("dense", sa.JSON(), nullable=False),
        sa.Column("sparse_indices", sa.JSON(), nullable=False),
        sa.Column("sparse_values", sa.JSON(), nullable=False),
        sa.Column("dense_normalized", sa.Boolean(), nullable=False),
        sa.Column("document_encoded", sa.Boolean(), nullable=False),
        sa.Column("dense_sha256", sa.String(length=64), nullable=False),
        sa.Column("sparse_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "dense_dimension = 768", name=op.f("ck_prepared_chunk_vectors_dense_dimension_target")
        ),
        sa.CheckConstraint(
            "dense_normalized = 1", name=op.f("ck_prepared_chunk_vectors_dense_is_normalized")
        ),
        sa.CheckConstraint(
            "document_encoded = 1",
            name=op.f("ck_prepared_chunk_vectors_sparse_is_document_encoding"),
        ),
        sa.CheckConstraint(
            "length(dense_sha256) = 64", name=op.f("ck_prepared_chunk_vectors_dense_sha256_length")
        ),
        sa.CheckConstraint(
            "length(sparse_sha256) = 64",
            name=op.f("ck_prepared_chunk_vectors_sparse_sha256_length"),
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["prepared_chunks.id"],
            name=op.f("fk_prepared_chunk_vectors_chunk_id_prepared_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prepared_revision_id"],
            ["prepared_revisions.id"],
            name=op.f("fk_prepared_chunk_vectors_prepared_revision_id_prepared_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id", name=op.f("pk_prepared_chunk_vectors")),
    )
    with op.batch_alter_table("prepared_chunk_vectors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prepared_chunk_vectors_prepared_revision_id"),
            ["prepared_revision_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prepared_chunk_vectors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prepared_chunk_vectors_prepared_revision_id"))

    op.drop_table("prepared_chunk_vectors")
    with op.batch_alter_table("deletion_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deletion_progress_document_id"))

    op.drop_table("deletion_progress")
    with op.batch_alter_table("candidate_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_evidence_prepared_revision_id"))
        batch_op.drop_index(batch_op.f("ix_candidate_evidence_candidate_id"))

    op.drop_table("candidate_evidence")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index("ix_audit_events_document_time")

    op.drop_table("audit_events")
    with op.batch_alter_table("work_operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_operations_state"))
        batch_op.drop_index(batch_op.f("ix_work_operations_prepared_revision_id"))
        batch_op.drop_index(batch_op.f("ix_work_operations_operation_type"))
        batch_op.drop_index("ix_work_operations_lease")
        batch_op.drop_index(batch_op.f("ix_work_operations_document_id"))
        batch_op.drop_index("ix_work_operations_claim")

    op.drop_table("work_operations")
    with op.batch_alter_table("revision_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revision_artifacts_prepared_revision_id"))

    op.drop_table("revision_artifacts")
    with op.batch_alter_table("publication_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publication_records_document_id"))

    op.drop_table("publication_records")
    with op.batch_alter_table("prepared_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prepared_pages_prepared_revision_id"))

    op.drop_table("prepared_pages")
    with op.batch_alter_table("prepared_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prepared_chunks_prepared_revision_id"))

    op.drop_table("prepared_chunks")
    with op.batch_alter_table("prepared_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prepared_candidates_prepared_revision_id"))
        batch_op.drop_index(batch_op.f("ix_prepared_candidates_matched_document_id"))

    op.drop_table("prepared_candidates")
    with op.batch_alter_table("index_outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_index_outbox_state"))
        batch_op.drop_index(batch_op.f("ix_index_outbox_prepared_revision_id"))
        batch_op.drop_index("ix_index_outbox_document_target")
        batch_op.drop_index(batch_op.f("ix_index_outbox_document_id"))
        batch_op.drop_index("ix_index_outbox_claim")

    op.drop_table("index_outbox")
    with op.batch_alter_table("formatter_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_formatter_batches_prepared_revision_id"))

    op.drop_table("formatter_batches")
    with op.batch_alter_table("extracted_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extracted_pages_prepared_revision_id"))

    op.drop_table("extracted_pages")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_document_id"))

    op.drop_table("decisions")
    with op.batch_alter_table("tombstones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tombstones_document_id"))

    op.drop_table("tombstones")
    with op.batch_alter_table("prepared_revisions", schema=None) as batch_op:
        batch_op.drop_index("ix_prepared_revisions_document_status")
        batch_op.drop_index(batch_op.f("ix_prepared_revisions_document_id"))

    op.drop_table("prepared_revisions")
    with op.batch_alter_table("idempotency_records", schema=None) as batch_op:
        batch_op.drop_index("ix_idempotency_records_resource")

    op.drop_table("idempotency_records")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_state"))
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index("ix_documents_collection_state_created")
        batch_op.drop_index("ix_documents_collection_sha_state")

    op.drop_table("documents")
    # ### end Alembic commands ###
