"""semantic intake catalog

Revision ID: 0001_semantic_intake
Revises:
Create Date: 2026-07-13 12:57:25.850460
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_semantic_intake"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_epochs",
        sa.Column("collection_key", sa.String(length=63), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("collection_key", name=op.f("pk_collection_epochs")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("normalized_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ANALYZING",
                "REVIEW_REQUIRED",
                "INGESTING",
                "INGEST_FAILED",
                "INGESTED",
                "REPLACING",
                "REPLACE_FAILED",
                "DELETING",
                "DELETE_FAILED",
                "CLEANUP_PENDING",
                "CLEANUP_FAILED",
                "REJECTED",
                "CANCELLED",
                "DELETED",
                name="document_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("collection_key", sa.String(length=63), nullable=False),
        sa.Column(
            "scan_state",
            sa.Enum(
                "PENDING",
                "CLEAN",
                "INFECTED",
                "ERROR",
                name="scan_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scan_engine", sa.String(length=100), nullable=True),
        sa.Column("scan_signature", sa.String(length=255), nullable=True),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploader_identity", sa.String(length=255), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("text_sha256", sa.String(length=64), nullable=True),
        sa.Column("analysis_revision", sa.Integer(), nullable=False),
        sa.Column("collection_epoch", sa.Integer(), nullable=True),
        sa.Column(
            "cleanup_target",
            sa.Enum(
                "ANALYZING",
                "REVIEW_REQUIRED",
                "INGESTING",
                "INGEST_FAILED",
                "INGESTED",
                "REPLACING",
                "REPLACE_FAILED",
                "DELETING",
                "DELETE_FAILED",
                "CLEANUP_PENDING",
                "CLEANUP_FAILED",
                "REJECTED",
                "CANCELLED",
                "DELETED",
                name="cleanup_target_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("replaced_by_document_id", sa.Uuid(), nullable=True),
        sa.Column("analysis_manifest_hash", sa.String(length=64), nullable=True),
        sa.Column("rejection_reason", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_documents_sha256_length")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_documents_size_bytes_nonnegative")),
        sa.ForeignKeyConstraint(
            ["replaced_by_document_id"],
            ["documents.id"],
            name=op.f("fk_documents_replaced_by_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_documents_idempotency_key")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_documents_collection_state", ["collection_key", "state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_documents_sha256"), ["sha256"], unique=False)
        batch_op.create_index(
            "ix_documents_sha256_collection_state",
            ["sha256", "collection_key", "state"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_documents_state"), ["state"], unique=False)
        batch_op.create_index("ix_documents_text_sha256", ["text_sha256"], unique=False)

    op.create_table(
        "document_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "COMPLETE",
                "FAILED",
                name="analysis_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("pipeline_fingerprint", sa.String(length=100), nullable=True),
        sa.Column("collection_epoch", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("text_sha256", sa.String(length=64), nullable=True),
        sa.Column("filename_warnings", sa.JSON(), nullable=False),
        sa.Column("semantic_complete", sa.Boolean(), nullable=False),
        sa.Column("classification_complete", sa.Boolean(), nullable=False),
        sa.Column("incomplete_reasons", sa.JSON(), nullable=False),
        sa.Column("screening_indexed", sa.Boolean(), nullable=False),
        sa.Column("auto_ingest_eligible", sa.Boolean(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("classified_count", sa.Integer(), nullable=False),
        sa.Column("overflow_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_document_analyses_revision_positive")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_analyses_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_analyses")),
        sa.UniqueConstraint(
            "document_id", "revision", name=op.f("uq_document_analyses_document_id")
        ),
    )
    with op.batch_alter_table("document_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_analyses_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "document_artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["document_analyses.id"],
            name=op.f("fk_document_artifacts_analysis_id_document_analyses"),
            ondelete="CASCADE",
        ),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_document_artifacts_sha256_length")),
        sa.CheckConstraint(
            "size_bytes > 0", name=op.f("ck_document_artifacts_size_bytes_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_artifacts")),
        sa.UniqueConstraint("analysis_id", "kind", name=op.f("uq_document_artifacts_analysis_id")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_document_artifacts_storage_key")),
    )
    with op.batch_alter_table("document_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_artifacts_analysis_id"), ["analysis_id"], unique=False
        )

    op.create_table(
        "analysis_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("matched_document_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("max_cosine", sa.Float(), nullable=False),
        sa.Column("strong_cosine_chunks", sa.Integer(), nullable=False),
        sa.Column("moderate_cosine_chunks", sa.Integer(), nullable=False),
        sa.Column("bm25_strong_placements", sa.Integer(), nullable=False),
        sa.Column("fused_score", sa.Float(), nullable=False),
        sa.Column("classified", sa.Boolean(), nullable=False),
        sa.Column("overflow", sa.Boolean(), nullable=False),
        sa.Column("matched_chunk_pairs", sa.JSON(), nullable=False),
        sa.Column("document_snapshot", sa.JSON(), nullable=False),
        sa.CheckConstraint("rank >= 1", name=op.f("ck_analysis_candidates_rank_positive")),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["document_analyses.id"],
            name=op.f("fk_analysis_candidates_analysis_id_document_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["matched_document_id"],
            ["documents.id"],
            name=op.f("fk_analysis_candidates_matched_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_candidates")),
        sa.UniqueConstraint(
            "analysis_id", "matched_document_id", name=op.f("uq_analysis_candidates_analysis_id")
        ),
    )
    with op.batch_alter_table("analysis_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_candidates_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_candidates_matched_document_id"),
            ["matched_document_id"],
            unique=False,
        )

    op.create_table(
        "analysis_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_analysis_chunks_chunk_index_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["document_analyses.id"],
            name=op.f("fk_analysis_chunks_analysis_id_document_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_analysis_chunks_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_chunks")),
        sa.UniqueConstraint(
            "analysis_id", "chunk_index", name=op.f("uq_analysis_chunks_analysis_id")
        ),
    )
    with op.batch_alter_table("analysis_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_chunks_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analysis_chunks_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "index_outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=True),
        sa.Column("collection_key", sa.String(length=63), nullable=False),
        sa.Column("collection_epoch", sa.Integer(), nullable=False),
        sa.Column(
            "target",
            sa.Enum(
                "ACTIVE",
                "SCREENING",
                name="index_target",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "UPSERT",
                "PUBLISH",
                "DELETE",
                name="index_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expected_points", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "DONE",
                "SUPERSEDED",
                name="outbox_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_index_outbox_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "collection_epoch >= 1",
            name=op.f("ck_index_outbox_collection_epoch_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_outbox")),
    )
    with op.batch_alter_table("index_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_index_outbox_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_index_outbox_document_target_epoch",
            ["document_id", "target", "collection_epoch"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_index_outbox_state"), ["state"], unique=False)
        batch_op.create_index("ix_index_outbox_state_id", ["state", "id"], unique=False)

    op.create_table(
        "intake_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_revision", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "KEEP",
                "REPLACE",
                "CANCEL",
                name="decision_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_document_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("advisory_override", sa.Boolean(), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_intake_decisions_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_document_id"],
            ["documents.id"],
            name=op.f("fk_intake_decisions_target_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intake_decisions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_intake_decisions_idempotency_key")),
    )
    with op.batch_alter_table("intake_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_intake_decisions_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "candidate_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["analysis_candidates.id"],
            name=op.f("fk_candidate_findings_candidate_id_analysis_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_findings")),
        sa.UniqueConstraint(
            "candidate_id", "role", name=op.f("uq_candidate_findings_candidate_id")
        ),
    )
    with op.batch_alter_table("candidate_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_findings_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "replacement_workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("new_document_id", sa.Uuid(), nullable=False),
        sa.Column("old_document_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PREPARING",
                "DELETING_OLD",
                "INGESTING_NEW",
                "SUCCEEDED",
                "FAILED",
                name="replacement_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["intake_decisions.id"],
            name=op.f("fk_replacement_workflows_decision_id_intake_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["new_document_id"],
            ["documents.id"],
            name=op.f("fk_replacement_workflows_new_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["old_document_id"],
            ["documents.id"],
            name=op.f("fk_replacement_workflows_old_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_replacement_workflows")),
        sa.UniqueConstraint(
            "new_document_id", name=op.f("uq_replacement_workflows_new_document_id")
        ),
    )
    with op.batch_alter_table("replacement_workflows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_replacement_workflows_old_document_id"),
            ["old_document_id"],
            unique=False,
        )

    op.create_table(
        "work_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum(
                "ANALYZE",
                "INGEST",
                "DELETE",
                "CLEANUP",
                name="operation_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="operation_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "phase",
            sa.Enum(
                "QUEUED",
                "EXTRACTING",
                "COMPARING",
                "AWAITING_DECISION",
                "DELETING_EXISTING",
                "INGESTING",
                "CLEANING_UP",
                "COMPLETE",
                name="operation_phase",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("replacement_id", sa.Uuid(), nullable=True),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_work_operations_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_work_operations_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["replacement_id"],
            ["replacement_workflows.id"],
            name=op.f("fk_work_operations_replacement_id_replacement_workflows"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_operations")),
        sa.UniqueConstraint(
            "document_id", "operation_type", "attempt", name=op.f("uq_work_operations_document_id")
        ),
    )
    with op.batch_alter_table("work_operations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_work_operations_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            "ix_work_operations_lease", ["state", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_operations_operation_type"), ["operation_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_work_operations_state"), ["state"], unique=False)
        batch_op.create_index(
            "ix_work_operations_state_created", ["state", "created_at"], unique=False
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_audit_events_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["work_operations.id"],
            name=op.f("fk_audit_events_operation_id_work_operations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_events_document_time", ["document_id", "occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index("ix_audit_events_document_time")

    op.drop_table("audit_events")
    with op.batch_alter_table("work_operations", schema=None) as batch_op:
        batch_op.drop_index("ix_work_operations_state_created")
        batch_op.drop_index(batch_op.f("ix_work_operations_state"))
        batch_op.drop_index(batch_op.f("ix_work_operations_operation_type"))
        batch_op.drop_index("ix_work_operations_lease")
        batch_op.drop_index(batch_op.f("ix_work_operations_document_id"))

    op.drop_table("work_operations")
    with op.batch_alter_table("replacement_workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_replacement_workflows_old_document_id"))

    op.drop_table("replacement_workflows")
    with op.batch_alter_table("candidate_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_findings_candidate_id"))

    op.drop_table("candidate_findings")
    with op.batch_alter_table("intake_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intake_decisions_document_id"))

    op.drop_table("intake_decisions")
    with op.batch_alter_table("index_outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_index_outbox_state_id")
        batch_op.drop_index(batch_op.f("ix_index_outbox_state"))
        batch_op.drop_index(batch_op.f("ix_index_outbox_document_id"))

    op.drop_table("index_outbox")
    with op.batch_alter_table("analysis_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_chunks_document_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_chunks_analysis_id"))

    op.drop_table("analysis_chunks")
    with op.batch_alter_table("analysis_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_candidates_matched_document_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_candidates_analysis_id"))

    op.drop_table("analysis_candidates")
    with op.batch_alter_table("document_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_artifacts_analysis_id"))

    op.drop_table("document_artifacts")
    with op.batch_alter_table("document_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_analyses_document_id"))

    op.drop_table("document_analyses")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_documents_text_sha256")
        batch_op.drop_index(batch_op.f("ix_documents_state"))
        batch_op.drop_index("ix_documents_sha256_collection_state")
        batch_op.drop_index(batch_op.f("ix_documents_sha256"))
        batch_op.drop_index("ix_documents_collection_state")

    op.drop_table("documents")
    op.drop_table("collection_epochs")
    # ### end Alembic commands ###
